### PR TITLE
Draft implementation of UbiquityStoreManagerBackupPolicy

### PR DESCRIPTION
**Pull request by Clstroud**
Adds UbiquityStoreManagerBackupPolicy as a type which can be used to configure whether or not backups should occur under varying circumstances.

UbiquityStoreManager now has a "backupPolicy" property and corresponding dictionary key that allow the developer to configure the circumstance(s), if any, that they would like their Core Data storage to be backed up to iCloud/iTunes.

The options are:

· **UbiquityStoreBackupPolicyAlways** - persistent store will be backed up to iCloud or iTunes
· **UbiquityStoreBackupPolicyLocalOnly** - persistent store will be permitted to back up ONLY if iCloud Sync is disabled
· **UbiquityStoreBackupPolicyNever** - persistent store will never be backed up to iCloud or iTunes

Many developers likely haven't needed this feature because their Core Data stores remain relatively small. However, with External Storage having been introduced in iOS 5+, certain scenarios may lead to enormous "support" files attempting to be synced across the network and into iCloud, which is clearly sub-optimal, especially if that data is already being synced by iCloud.

**Note:** I did refactor some of the constants and typedef declarations to be closer in line with _my_ personal understanding of what Apple encourages. Due to style preferences (or wrongness on my part) I completely understand if those changes aren't desirable for some reason. Also, this seems to work fine for me in my app's environment but I'm certain there are edge cases out there somewhere that I am not aware of and can't anticipate… but I tried my best to keep it non-invasive :-) It may make more sense to deny this PR and clone the branch into your repository rather than merging into master. Not quite sure what the standard protocol is for a contributor attempting to hand over an experimental feature rather than a quick bug fix.

### CODE REVIEW

**Comment by lhunath** [comment]
Thank you very much for your effort and input; though I don't think it should be USM's responsibility to set the NSURLIsExcludedFromBackupKey flag on the local store URL.  If that's the effect you desire, do so in your delegate's storeWillLoad.  This pull request, although well intended, adds a lot of complexity to an already very complex controller.  I'm hoping to make it simpler over time, not more involved :-).

This should suffice for you:

```
- (void)ubiquityStoreManager:(UbiquityStoreManager *)manager willLoadStoreIsCloud:(BOOL)isCloudStore {

    [manager.localStoreURL setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:nil];
```

**Comment by Clstroud** [comment]
Handling the external storage directory is a _little_ more involved than that snippet, but I understand your point and take no offense :-)

Though in the spirit of discussion I'm curious why you wouldn't find this to be a logical addition? To my knowledge there is nothing stopping iCloud Backup from backing up the local store in addition to hosting it in your regular "sync" storage space, correct? I don't recall seeing any explicit mention of iCloud sync preventing that redundancy, but perhaps I missed it.

Assuming it doesn't, then since USM will be managing the persistent store for us, it seems like an excellent candidate for an optional feature to let it set that backup flag as dictated by the store's state and backup policy. USM is serving as the level of abstraction that, among other things, is interfacing the filesystem. To me that positions it as the best level in which to handle this _for_ developers with very little fuss.

Of course I agree that USM should be as simple as necessary, just not simpler ;-) _My_ needs certainly don't match the needs of the masses, so I will at the very least leave my branch around just in case others second the notion and/or need the code.

Thanks Maarten!

**Comment by lhunath** [comment]
Note that the local store is never synced using iCloud, so having it backed up to iCloud isn't really a redundancy at all.  Only the cloud store is synced via iCloud, and this store should not be backed up by iCloud.  If it is, I would consider that a bug and a worthy thing to deal with in USM as per your rational.

**Comment by Clstroud** [comment]
Understood. In that case I will keep an eye on it during my sync testing and will report back if I see otherwise. Thanks for clarifying :-)

**Pull request closed without merging**
